### PR TITLE
Ft business info 183734469

### PR DESCRIPTION
**Pull request by Naochrist**
#### What does this PR do?
It performs Create, Read and Update operation for Business Information Model in Account Management 
A test file is written to check if the endpoints are working as intended. 

#### How should this be manually tested?
It can be tested using Postman. To check if the test is working, you would need a token.

#### Questions:

### CODE REVIEW

**Review by oolushola — CHANGES_REQUESTED** [review]
There are quite a number of things that are not right about this endpoints. 

- The middleware token is disabled on all endpoints, which exposes it to everybody. That's a security risk. 
- On the model, I noticed you are using the snake case in naming the field name, nah - the ideal field name standard is camel case, e.g, where you have cac_no, please change it to cacNo. 
- Did you follow through the template PR template I shared with you guys?

**Comment by oolushola** [comment]
I already reviewed your updated PR, I noticed the following

1. On the app.js, remove everything you commented out. 
2 "The middleware token is disabled on all endpoints, which exposes it to everybody. That's a security risk". I gave you this feedback the last time, It wasn't worked on. 
3. Why are you not giving your PR a description? I shared a template with you.

**Comment by Naochrist** [comment]
1. I will work on that now, it was an oversight. 
2. the middleware token were actually uncommented. kindly review the business information route I worked on
3. Noted, moving forward i will refer to the template when creating a PR.

Thanks

**Review by oolushola — APPROVED** [review]

**Pull request merged**
